version: '3.1'
name: cicd

services:
  # bitbucket ci/cd
  # bitbucket:
  #   container_name: runner-
  #   image: docker-public.packages.atlassian.com/sox/atlassian/bitbucket-pipelines-runner:1
  #   environment:
  #     - ACCOUNT_UUID=
  #     - RUNNER_UUID=
  #     - OAUTH_CLIENT_ID=
  #     - OAUTH_CLIENT_SECRET=
  #     - RUNTIME_PREREQUISITES_ENABLED=true
  #     - WORKING_DIRECTORY=/tmp
  #   volumes:
  #     - /tmp:/tmp
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - /var/lib/docker/containers:/var/lib/docker/containers:ro
  #     - ./resolv.conf:/etc/resolv.conf

  # others ci/cd

  # Alpine APK Registry Proxy
  alpine-proxy:
    container_name: alpine-proxy
    image: cicd-alpine-proxy:1
    build:
      context: ./alpine-proxy
    ports:
      - 3030:3030
    volumes:
      - ./_data/alpine-proxy:/app/data
      - ./resolv.conf:/etc/resolv.conf
    restart: unless-stopped
    environment:
      - PORT=3030
      - REPOSITORY_URL=https://dl-cdn.alpinelinux.org

  # Local Docker private registry
  docker-registry:
    container_name: docker-registry
    image: cicd-docker-registry:1
    build:
      context: ./registry
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    restart: unless-stopped
    volumes:
      - ./_data/registry:/var/lib/registry
      - ./resolv.conf:/etc/resolv.conf

  # Local NPM private registry and proxy
  verdaccio:
    container_name: verdaccio
    image: cicd-verdaccio:1
    build:
      context: ./verdaccio
      dockerfile: Dockerfile
    ports:
      - 4873:4873
    volumes:
      - ./_data/verdaccio:/verdaccio/storage
      - ./verdaccio/plugins:/verdaccio/plugins
      - ./resolv.conf:/etc/resolv.conf
    restart: unless-stopped
    environment:
      NPM_TOKEN: /run/secrets/npm_token
      VERDACCIO_APPDIR: /opt/verdaccio
      VERDACCIO_USER_NAME: verdaccio
      VERDACCIO_PROTOCOL: http
      VERDACCIO_PORT: 4873
      VERDACCIO_USER_UID: 10001

# secret keys
secrets:
  npm_token:
    file: ./npm_token.txt

# network
networks: 
  default:
    name: cicd
    driver: bridge